INSERT INTO referans (id, adi, kodu, tipi) VALUES (1, 'EDAMIS', 1, 'ARAC');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (2, 'SDMX', 2, 'ARAC');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (3, 'WEB', 3, 'ARAC');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (4, 'ESS Metadata Handler', 4, 'ARAC');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (5, 'Excel', 5, 'ARAC');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (6, 'E-posta', 6, 'ARAC');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (7, 'IILMT', 7, 'ARAC');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (8, 'CRF Reporter', 8, 'ARAC');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (9, 'Bilgi Talebi', 9, 'ARAC');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (10, 'KTB', 10, 'ARAC');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (11, 'Soru Formu', 11, 'ARAC');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (12, 'EIONET', 12, 'ARAC');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (13, 'UNIDEMO', 13, 'ARAC');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (14, 'ICT', 14, 'ARAC');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (15, 'Resmi Yazışma', 15, 'ARAC');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (16, 'TÜİK-YDB', 16, 'ARAC');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (17, 'Kişi', 1, 'ISTATISTIKI_BIRIM_DUZEY');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (18, 'Hanehalkı', 2, 'ISTATISTIKI_BIRIM_DUZEY');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (19, 'İşyeri', 3, 'ISTATISTIKI_BIRIM_DUZEY');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (20, 'Diğer', 4, 'ISTATISTIKI_BIRIM_DUZEY');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (21, 'Türkiye', 5, 'COGRAFI_DUZEY');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (22, 'Kent-Kır', 10, 'COGRAFI_DUZEY');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (23, 'İbbs-Düzey1', 15, 'COGRAFI_DUZEY');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (24, 'İbbs-Düzey2', 20, 'COGRAFI_DUZEY');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (25, 'İbbs-Düzey3 (İl)', 25, 'COGRAFI_DUZEY');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (26, 'İbbs-Düzey3 (Sadece Seçili Iller)', 30, 'COGRAFI_DUZEY');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (27, 'İbbs-Düzey4 (İlçe)', 35, 'COGRAFI_DUZEY');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (28, 'Büyükşehir Belediye', 40, 'COGRAFI_DUZEY');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (29, 'Belediye', 45, 'COGRAFI_DUZEY');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (30, 'Belde-Köy', 50, 'COGRAFI_DUZEY');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (31, 'Sandık Kurulu', 55, 'COGRAFI_DUZEY');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (32, 'Dağıtımı Yok', 60, 'COGRAFI_DUZEY');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (33, 'ODTÜ', 182, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (34, 'Kompost tesisleri', 171, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (35, 'Ulaştirma Ve Altyapi Bakanliği Karayolu Düzenleme Genel Müdürlüğü', 20, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (36, 'Gülbirlik', 68, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (37, 'Fide Üreticileri Alt Birliği', 47, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (38, 'Enerji Piyasası Düzenleme Kurumu', 183, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (39, 'Ticaret Bakanliği (Gümrük Ve Ticaret) Esnaf Ve Sanatkarlar Genel Müdürlüğü', 29, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (40, 'Afet ve Acil Durum Yönetim Başkanlığ', 186, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (41, 'ENERJİ VE TABİİ KAYNAKLAR BAKANLIĞI', 161, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (42, 'Tarim Ve Orman Bakanliği (Gida, Tarim Ve Hayvancilik)  Toprak Reformu Genel Müdürlüğü', 59, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (43, 'Bankacilik Düzenleme Ve Denetleme Kurumu,Sermaye Piyasasi Kurulu, Hazine Ve Maliye Bakanliği (Hazine),Teskomb,Türkiye Cumhuriyet Merkez Bankasi,Türkiye Odalar Ve Borsalar Birliği', 53, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (44, 'Yaş Sebze Ve Meyve Halleri', 9, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (45, 'Kredi ve Yurtlar Kurumu Genel Müdürlüğü', 187, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (46, 'Tarim Ve Kirsal Kalkinmayi Destekleme Kurumu', 65, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (47, 'Trakya Birlik Genel Müdürlüğü', 45, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (48, 'Fidan Üreticileri Alt Birliği', 74, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (49, 'Tohum Yetiştiricileri Alt Birliği', 44, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (50, 'TARIM TAHMİN KOMİTESİ ', 147, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (51, 'HAZİNE VE MALİYE BAKANLIĞI  SİGORTA DENETLEME KURULU', 143, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (52, 'TÜRKİYE CUMHURİYET MERKEZ BANKASI', 106, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (53, 'Kültür Ve Turizm Bakanliği Kütüphaneler Ve Yayimlar Genel Müdürlüğü', 21, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (54, 'MİLLETVEKİLİ SEÇİM İSTATİSTİKLERİ MAHALLİ İDARELER SEÇİM İSTATİSTİKLERİ', 178, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (55, 'İGSAŞ, Gemlik Gübre ve diğer gübre fabrikaları ', 167, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (56, 'Sağlık Bakanlığı', 101, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (57, 'Emniyet Genel Müdürlüğü İstatistikleri', 99, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (58, 'Yükseköğretim Kurulu Başkanliği', 17, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (59, 'İlaç Endüstrisi İşverenler sendikası', 108, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (60, 'Tarim Ve Orman Bakanliği (Gida, Tarim Ve Hayvancilik) Gida Ve Kontrol Genel Müdürlüğü', 24, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (61, 'HAZİNE VE MALİYE BAKANLIĞI  MUHASEBAT VE MALİ KONTROL GENEL MÜDÜRLÜĞÜ VE KAMU FİNANSMANI GENEL MÜDÜRLÜĞÜ', 149, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (62, 'Yükseköğretim Kurulu Başkanliği Kredi Ve Yurtlar Kurumu', 13, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (63, 'Pegasus Hava Yolları', 193, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (64, 'Milli Eğitim Bakanliği', 36, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (65, 'Süs Bitkileri Üreticileri Alt Birliği', 37, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (66, 'Vakıflar Genel Müdürlüğü', 184, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (67, 'Cam fabrikaları', 165, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (68, 'Türkiye İhracatçılar Meclisi', 134, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (69, 'BOTAŞ ve özel firmalar', 133, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (70, 'Aile, Çalişma Ve Sosyal Hizmetler Bakanliği', 51, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (71, 'Vakiflar Genel Müdürlüğü', 49, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (72, 'YTB', 188, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (73, 'Avrupa Birliği İstatistik Ofisi Veri Tabanı', 100, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (74, 'İçişleri Bakanlığı Emniyet Genel Müdürlüğü', 96, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (75, 'Metan geri kazanımı yapan tesisler', 172, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (76, 'Adalet Bakanlığı', 150, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (77, 'Çukobirlik  Genel Müdürlüğü', 28, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (78, 'Fiskobirlik Genel Müdürlüğü', 70, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (79, 'Ticaret Bakanliği Risk Yönetimi Ve Kontrol Genel Müdürlüğü', 26, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (80, 'Türkiye Jokey Kulübü Müşterek Bahisler Müdürlüğü', 117, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (81, 'Türkiye Bankalar Birliği', 141, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (82, 'GSM operatörleri', 138, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (83, 'Milli Savunma Bakanlığı', 94, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (84, 'Türkiye İş Kurumu', 160, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (85, 'Devlet Arşivleri Başkanliği', 19, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (86, 'ZİRAAT ODASI BAŞKANLIĞI', 129, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (87, 'Türkiye Süt Üreticileri Merkez Birliği', 60, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (88, 'Ticaret Bakanliği (Gümrük Ve Ticaret)', 3, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (89, 'Tütün ve Alkol Piyasası Düzenleme Kurumu', 107, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (90, 'Sanayi Ve Teknoloji Bakanliği', 40, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (91, 'Hazine Ve Maliye Bakanliği (Maliye)', 63, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (92, 'Toprak Mahsulleri Ofisi;Çaykur;Şeker Dairesi Başkanlığı; Tütün ve Alkol Dairesi Başkanlığı', 120, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (93, 'Sağlik Bakanliği', 23, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (94, 'Türkiye Büyük Millet Meclisi Başkanliği', 58, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (95, 'Uluslar Arasi Yatirimcilar Derneği (Yased)', 32, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (263, 'Üç Aylık', 10, 'PERIYOT');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (96, 'Nüfus Ve Vatandaşlik İşleri Genel Müdürlüğü Mekansal Adres Kayit Sistemi (Maks)', 52, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (97, 'GENÇLİK VE SPOR BAKANLIĞI  SPOR GENEL MÜDÜRLÜĞÜ', 154, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (98, 'TARIM VE ORMAN BAKANLIĞI (GIDA, TARIM VE HAYVANCILIK) HAYVANCILIK GENEL MÜDÜRLÜĞÜ', 122, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (99, 'Türksat Uydu Haberleşme Kablo TV ve İşletme A.Ş.', 115, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (100, 'Maden ve Petrol İşleri Genel Müdürlüğü (MAPEG)', 174, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (101, 'KTB', 187, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (102, 'Tapu Ve Kadastro Genel Müdürlüğü', 77, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (103, 'Onur Air', 194, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (104, 'Bilgi Teknolojileri ve İletişim Kurumu', 113, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (105, 'Banka Vakıf Sandıkları', 185, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (106, 'Karadeniz Birlik Genel Müdürlüğü', 4, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (107, 'Kültür Ve Turizm Bakanliği', 72, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (108, 'Finansal Kiralama Faktoring ve Finansman Şirketleri Birliği (FİDER)', 131, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (109, 'Jandarma Genel Komutanliği', 85, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (110, 'Türkiye Odalar Ve Borsalar Birliği', 90, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (111, 'Kamu Hastaneleri Genel Müdürlüğü', 69, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (112, 'Toprak Mahsülleri Ofisi (Tmo)', 62, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (113, 'Karayolları Genel Müdürlüğü', 110, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (114, 'Eurostat', 136, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (115, 'EMNİYET GENEL MÜDÜRLÜĞÜ', 137, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (116, 'Çevre Ve Şehircilik Bakanliği', 71, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (117, 'Türkiye Noterler Birliği, Emniyet Genel Müdürlüğü', 46, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (118, 'Nüfus Ve Vatandaşlik İşleri Genel Müdürlüğü', 27, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (119, 'Tapu Ve Kadastro Genel Müdürlüğü Yabanci İşler Daire Başkanliği', 25, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (120, 'Ulaştırma ve Altyapı Bakanlığı', 170, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (121, 'Diyanet İşleri Başkanliği', 30, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (122, 'Türkiye Elektrik İletim Anonim Şirketi Genel Müdürlüğü', 7, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (123, 'EMEKLİLİK GÖZETİM MERKEZİ', 145, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (124, 'TARSİM Tarım Sigortaları Havuzu', 124, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (125, 'Diyanet İşleri Başkanlığı Hac ve Umre İşleri Genel Müdürlüğü', 119, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (126, 'Aile,Çalışma ve Sosyal Hizmetler Bakanlığı İşgücü Genel Müdürlüğü', 93, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (127, 'Marmarabirlik', 83, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (128, 'Hacettepe Üniversitesi Nüfus Etütleri Enstitüsü', 102, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (129, 'Tarim Ve Orman Bakanliği (Gida, Tarim Ve Hayvancilik) Hayvancilik  Genel Müdürlüğü', 76, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (130, 'İçişleri Bakanliği Mahalli İdareler Genel Müdürlüğü', 67, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (131, 'TARIM VE ORMAN BAKANLIĞI ', 122, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (132, 'Çimento fabrikaları ve Çimento Müstahsilleri Birliği', 163, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (133, 'Sağlık Bakanlığı', 159, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (134, ' FİDB Tarımsal Fiyat İstatistikleri Grup Başkanlığı', 142, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (135, 'Ulaştırma ve Altyapı Bakanlığı', 175, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (136, 'Türk Hava Yolları', 112, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (137, 'Tarim Ve Orman Bakanliği (Gida, Tarim Ve Hayvancilik) Şeker Dairesi Başkanliği', 31, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (138, 'Tarim Ve Orman Bakanliği (Gida, Tarim Ve Hayvancilik) Bitkisel Üretim Genel Müdürlüğü', 18, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (139, 'Turkuvaz Dağıtım', 116, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (140, 'Türk İşbirliği ve Koordinasyon Ajansı', 177, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (141, 'Bankacilik Düzenleme Ve Denetleme Kurumu', 38, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (142, 'Ticaret Bakanlığı', 130, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (143, 'İçişleri Bakanlığı', 162, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (144, 'Aile, Çalışma ve Sosyal Hizmetler Bakanlığı, Engelli ve Yaşlı Hizmetleri Genel Müdürlüğü', 95, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (145, 'ETİ Alüminyum', 169, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (146, 'ERDEMİR, İSDEMİR, KARDEMİR', 168, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (147, 'T.C. MERKEZ BANKASI', 106, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (148, 'Üretici Birlikleri', 91, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (149, 'Tarim Ve Orman Bakanliği (Gida, Tarim Ve Hayvancilik)', 88, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (150, 'İçişleri Bakanlığı Göç İdaresi Genel Müdürlüğü', 92, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (151, 'Kültür Ve Turizm Bakanliği Kütüphane Ve Yayimlar Genel Müdürlüğü', 80, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (152, ' Sanayi ve Teknoloji Bakanlığı/OSB Genel Müdürlüğü', 173, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (153, 'Tarım ve Orman Bakanlığı', 122, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (154, 'Türkiye Cumhuriyet Merkez Bankasi', 22, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (155, 'Tarim Ve Orman Bakanliği (Orman Ve Su İşleri) Bilgi İşlem Daire Başkanliği', 73, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (156, 'Ölçme, Seçme Ve Yerleştirme Merkezi Başkanliği', 56, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (157, 'Türkiye Cumhuriyet Merkez Bankası', 106, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (158, 'Amerika Birleşik Devletleri Nüfus Bürosu (US Census Bureau)', 103, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (159, 'Kültür Ve Turizm Bakanliği Kültür Varliklari Ve Müzeler Genel Müdürlüğü', 54, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (160, 'SERMAYE PİYASASI KURULU', 144, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (161, 'Çaykur Genel Müdürlüğü', 50, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (162, 'TEDAŞ', 179, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (163, 'Emniyet Genel Müdürlüğü, Jandarma Genel Komutanliği, Adalet Bakanliği Ceza Ve Tevkifevleri Genel Müdürlüğü, Genelkurmay Başkanliği, Tüik Ölüm Nedeni', 8, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (164, 'TMSF', 191, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (241, 'Avrupa Komisyonu Yıllık Raporları', 7, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (242, 'Dünya Bankası', 8, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (165, 'BANKACILIK DÜZENLEME VE DENETLEME KURUMU,SERMAYE PİYASASI KURULU, HAZİNE VE MALİYE BAKANLIĞI (HAZİNE),TESKOMB,TÜRKİYE ODALAR VE BORSALAR BİRLİĞİ', 126, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (166, 'Adalet Bakanliği Adli Sicil Ve İstatistik Genel Müdürlüğü', 1, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (167, 'İGSAŞ, Gemlik Gübre ve diğer gübre fabrikaları ', 166, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (168, 'İçişleri Bakanliği Sivil Toplumla İlişkiler Genel Müdürlüğü', 16, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (169, 'Gençlik ve Spor Bakanlığı Kredi ve Yurtlar Genel Müdürlüğü', 97, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (170, 'Kültür Ve Turizm Bakanliği Telif Haklari Genel Müdürlüğü', 34, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (171, 'Hazine Ve Maliye Bakanliği (Hazine) Kamu Finansmani Genel Müdürlüğü', 10, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (172, 'BORSA İSTANBUL', 105, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (173, 'Gençlik ve Spor Bakanlığı Spor Toto Teşkilat Başkanlığı', 118, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (264, 'Altı Aylık', 15, 'PERIYOT');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (174, 'TİCARİ BANKALAR (HALK BANKASI, ZİRAAT BANKASI, VAKIFLAR BANKASI, İŞ BANKASI, GARANTİ BBVA, DENİZ BANK, İNG BANK, HSBC, AKBANK, YAPI KREDİ BANKASI, QNB FİNANSBANK, TEB)', 104, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (175, 'Sağlık Bakanlığı', 101, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (176, 'Türkiye Sigorta, Reasürans ve Emeklilik Şirketleri Birliği', 158, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (177, 'Ticaret Bakanliği (Ekonomi)', 55, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (178, 'Devlet Su İşleri Genel Müdürlüğü', 48, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (179, 'Savunma Sanayi Başkanlığı', 180, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (180, 'Tarim Sigortalari Havuz İşletmesi Anonim Şirketi', 15, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (181, 'TUBİTAK', 140, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (182, 'Balik Hal Ve Tesisleri', 5, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (183, 'TÜRKİYE NOTERLER BİRLİĞİ,', 127, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (184, 'Tarim Ve Orman Bakanliği (Orman Ve Su İşleri) Orman Genel Müdürlüğü', 14, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (185, 'İçişleri BakanlığıGöç İdaresi Genel Müdürlüğü', 92, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (186, 'Milli Kütüphane Başkanliği', 6, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (187, 'TCMB', 106, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (188, 'Kireç Sanayicileri Derneği ', 164, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (189, 'Otomobil Distribütörler Derneği', 109, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (190, 'TARIM SİGORTALARI HAVUZ İŞLETMESİ ANONİM ŞİRKETİ', 189, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (191, 'Bilgi Teknolojileri ve İletişim Kurumu', 113, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (192, 'Aile,Çalışma ve Sosyal Hizmetler Bakanlığı  Engelli ve Yaşlı Hizmetleri Genel Müdürlüğü ve Çocuk Hizmetleri Genel Müdürlüğü', 95, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (193, 'Gelir İdaresi Başkanliği', 79, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (194, 'Tarim Ve Kredi Kooperatifleri Merkez Birliği', 84, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (195, 'SGK', 139, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (196, 'Kültür Ve Turizm Bakanliği Opera Ve Bale Genel Müdürlüğü', 75, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (197, 'Kültür ve Turizm Bakanlığı Vakıflar Genel Müdürlüğü', 151, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (198, 'Çiçek Kooperatifleri', 61, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (199, 'Türk Telekom A.ş.', 114, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (200, 'Emniyet Genel Müdürlüğü, Jandarma Genel Komutanliği, Trafik Sigortalari Bilgi Merkezi (Tramer)', 81, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (201, 'Hacettepe Üniversitesi Nüfus Etütleri Enstitüsü', 102, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (202, 'Enerji Piyasası Düzenleme Kurumu, Devlet ve Su İşleri Genel Müdürlüğü, Tarım Sigortaları Havuzu', 121, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (203, 'Yüksek Seçim Kurulu Başkanliği', 57, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (204, 'DASK', 190, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (205, 'Milli Savunma Bakanlığı', 156, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (206, 'Kooperatif ve birlikler', 123, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (207, 'TETAŞ', 132, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (208, 'Tiftikbirlik', 64, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (209, 'Enerji ve Tabii Kaynaklar Bakanlığı', 161, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (210, 'Tarım ve Orman Bakanlığı', 122, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (211, 'Kültür ve Turizm Bakanlığı Müzik ve Sahne Sanatları Genel Müdürlüğü', 153, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (212, 'Ticaret Bakanliği (Gümrük Ve Ticaret) Esnaf Ve Sanatkarlar Genel Müdürlüğü İç Ticaret Genel Müdürlüğü', 33, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (213, 'Tapu Ve Kadastro Genel Müdürlüğü (Takbis)', 82, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (214, 'Basın İlan Kurumu', 155, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (215, 'Devlet Demiryolları Genel Müdürlüğü', 111, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (216, 'Hazine Ve Maliye Bakanliği Muhasebat Genel Müdürlüğü', 43, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (217, 'Tariş', 78, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (218, 'Ticaret Borsalari', 86, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (219, 'Bankacılık Düzenleme ve Denetleme Kurumu', 176, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (220, 'Türkiye İş Kurumu Genel Müdürlüğü', 11, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (221, 'Enerji ve Tabii Kaynaklar Bakanlığı', 161, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (222, 'Sosyal Güvenlik Kurumu', 35, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (223, 'Emniyet Genel Müdürlüğü', 41, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (224, 'Ulaştırma Denizcilik ve Haberleşme Bakanlığı', 128, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (225, 'TÜRKİYE SİGORTALAR BİRLİĞİ', 146, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (226, 'Tarim Ve Orman Bakanliği (Gida, Tarim Ve Hayvancilik) Tütün Ve Alkol Dairesi Başkanliği', 66, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (227, 'Milli Eğitim Bakanliği Strateji Geliştirme Başkanliği', 42, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (228, 'T.C. Cumhurbaşkanliği Strateji Ve Bütçe Başkanliği', 12, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (229, 'Kültür Ve Turizm Bakanliği Güzel Sanatlar Genel Müdürlüğü', 89, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (230, 'Tohum Sanayicileri Ve Üreticileri Alt Birliği', 87, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (231, 'Orman Su İşler Bakanlığı - Korunan Alanlar Genel Müdürlüğü', 152, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (232, 'Devlet Personel Başkanlığı İstatistikleri', 98, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (233, 'Deneme', 2, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (234, 'Ziraat Bankasi Genel Müdürlüğü', 39, 'KAYNAK_KURUM');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (235, 'EUROSTAT', 1, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (236, 'UNFCCC (Birleşmiş Milletler İklim Değişikliği Çerçeve Sözleşmesi) , EEA (Avrupa Çevre Ajansı)', 2, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (237, 'OECD', 3, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (238, 'UNECE', 4, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (239, 'FAO', 5, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (240, 'Birleşmiş Milletler ve bağlı kuruluşları (WHO,UNICEF,UNDP, UNSD,UNECE vb.)', 6, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (243, 'Birleşmiş Milletler ve bağlı kuruluşları (WHO,UNICEF,UNECE vb.)', 9, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (244, 'Birleşmiş Milletler ve bağlı kuruluşları (WHO,UNICEF,UNSD,UNIGME,UNECE vb.)', 10, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (245, 'IMF', 11, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (246, 'Alüminyum birliği', 12, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (247, 'SESRIC', 13, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (248, 'Birleşmiş Milletler ve bağlı kuruluşları (WHO,UNICEF,UNSD,UNECE vb.)', 14, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (249, 'EİT', 15, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (250, 'UN', 16, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (251, 'Birleşmiş Milletler', 17, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (252, 'ITC-Intracen, IMF, FAO, EİT, IRF (Uluslararası Yol Federasyonu)', 18, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (253, 'DG ECFIN', 19, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (254, 'EKOSOK himayesinde düzenlenen Yüksek Düzeyli Siyasi Forum -HLPF''ye', 20, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (255, 'BM Özelleşmiş Kuruluşlarına: (Bu kuruluşlardan gelen tekil ya da çoklu göstegre bazlı veri talepleri kapsamında iletilmiştir.)', 21, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (256, 'ILO', 22, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (257, 'UNESCO', 23, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (258, 'WHO', 24, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (259, 'UNWTO', 25, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (260, 'EUROSTAT (UOE)', 26, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (261, 'International Telecommunication Union (ITU)', 27, 'KURULUS');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (262, 'Aylık', 5, 'PERIYOT');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (265, 'Yıllık', 20, 'PERIYOT');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (266, 'İki Yıllık', 25, 'PERIYOT');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (267, 'Üç Yıllık', 30, 'PERIYOT');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (268, 'Dört Yıllık', 35, 'PERIYOT');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (269, 'Beş Yıllık', 40, 'PERIYOT');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (270, 'On Yıllık', 45, 'PERIYOT');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (271, 'Belirsiz', 50, 'PERIYOT');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (272, 'Günlük', 1, 'PERIYOT');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (273, 'Dağıtım Yok', 55, 'PERIYOT');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (274, 'Tablo Sayıları kontrol edilir', 1, 'VALIDASYON_TIPI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (275, 'Tablo Adları ve Alan Sayıları kontrol edilir', 2, 'VALIDASYON_TIPI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (276, 'Alan Adları', 3, 'VALIDASYON_TIPI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (277, 'Tipleri ve Doluluğu kontrol edilir', 4, 'VALIDASYON_TIPI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (278, 'Tablolardaki Satır Sayıları kontrol edilir', 5, 'VALIDASYON_TIPI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (279, 'Temel Değişkenlerin Tanımlayıcı İstatistikler kontrol edilir', 6, 'VALIDASYON_TIPI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (280, 'Mükerrer kayıtlar kontrol edilir', 7, 'VALIDASYON_TIPI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (281, 'Diğer', 1000, 'VALIDASYON_TIPI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (282, 'Ftp', 1, 'VERI_AKTARIM_BICIMI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (283, 'Web Servis', 2, 'VERI_AKTARIM_BICIMI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (284, 'Taşınabilir Disk (Cd, Flash)', 3, 'VERI_AKTARIM_BICIMI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (285, 'Diğer', 4, 'VERI_AKTARIM_BICIMI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (286, 'Mikro', 1, 'VERI_DUZEYI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (287, 'Makro', 2, 'VERI_DUZEYI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (288, 'Dump', 1, 'VERI_KAYNAK_BICIMI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (289, 'Txt', 2, 'VERI_KAYNAK_BICIMI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (290, 'XML/JSON', 3, 'VERI_KAYNAK_BICIMI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (291, 'Excel', 4, 'VERI_KAYNAK_BICIMI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (292, 'Diğer', 5, 'VERI_KAYNAK_BICIMI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (293, 'Girdi Verisi', 1, 'VERI_KULLANIM_AMACI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (294, 'Çerçeve Oluşturma', 2, 'VERI_KULLANIM_AMACI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (295, 'Kontrol/İmputasyon', 3, 'VERI_KULLANIM_AMACI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (296, 'Diğer', 4, 'VERI_KULLANIM_AMACI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (297, 'Önceden zamanlanmış/planlanmış', 1, 'VERI_TALEP_BICIMI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (298, 'Resmi yazı', 2, 'VERI_TALEP_BICIMI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (299, 'E-posta', 3, 'VERI_TALEP_BICIMI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (300, 'Telefon', 4, 'VERI_TALEP_BICIMI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (301, 'Diğer', 1000, 'VERI_TALEP_BICIMI');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (302, 'File Server', 2, 'VERININ_TUTULDUGU_YER');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (303, 'Veritabanı', 1, 'VERININ_TUTULDUGU_YER');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (304, 'Sas Server', 3, 'VERININ_TUTULDUGU_YER');
INSERT INTO referans (id, adi, kodu, tipi) VALUES (305, 'Diğer', 1000, 'VERININ_TUTULDUGU_YER');