INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 1, 'EDAMIS', 'ARAC');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 2, 'SDMX', 'ARAC');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 3, 'WEB', 'ARAC');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 4, 'ESS Metadata Handler', 'ARAC');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 5, 'Excel', 'ARAC');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 6, 'E-posta', 'ARAC');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 7, 'IILMT', 'ARAC');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 8, 'CRF Reporter', 'ARAC');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 9, 'Bilgi Talebi', 'ARAC');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 10, 'KTB', 'ARAC');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 11, 'Soru Formu', 'ARAC');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 12, 'EIONET', 'ARAC');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 13, 'UNIDEMO', 'ARAC');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 14, 'ICT', 'ARAC');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 15, 'Resmi Yazışma', 'ARAC');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 16, 'TÜİK-YDB', 'ARAC');