INSERT INTO arac(id, kodu, adi) VALUES (1, 1, 'EDAMIS');
INSERT INTO arac(id, kodu, adi) VALUES (2, 2, 'SDMX');
INSERT INTO arac(id, kodu, adi) VALUES (3, 3, 'WEB');
INSERT INTO arac(id, kodu, adi) VALUES (4, 4, 'ESS Metadata Handler');
INSERT INTO arac(id, kodu, adi) VALUES (5, 5, 'Excel');
INSERT INTO arac(id, kodu, adi) VALUES (6, 6, 'E-posta');
INSERT INTO arac(id, kodu, adi) VALUES (7, 7, 'IILMT');
INSERT INTO arac(id, kodu, adi) VALUES (8, 8, 'CRF Reporter');
INSERT INTO arac(id, kodu, adi) VALUES (9, 9, 'Bilgi Talebi');
INSERT INTO arac(id, kodu, adi) VALUES (10, 10, 'KTB');
INSERT INTO arac(id, kodu, adi) VALUES (11, 11, 'Soru Formu');
INSERT INTO arac(id, kodu, adi) VALUES (12, 12, 'EIONET');
INSERT INTO arac(id, kodu, adi) VALUES (13, 13, 'UNIDEMO');
INSERT INTO arac(id, kodu, adi) VALUES (14, 14, 'ICT');
INSERT INTO arac(id, kodu, adi) VALUES (15, 15, 'Resmi Yazışma');
INSERT INTO arac(id, kodu, adi) VALUES (16, 16, 'TÜİK-YDB');