INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 5, 'Türkiye', 'COGRAFI_DUZEY');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 10, 'Kent-Kır', 'COGRAFI_DUZEY');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 15, 'İbbs-Düzey1', 'COGRAFI_DUZEY');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 20, 'İbbs-Düzey2', 'COGRAFI_DUZEY');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 25, 'İbbs-Düzey3 (İl)', 'COGRAFI_DUZEY');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 30, 'İbbs-Düzey3 (Sadece Seçili Iller)', 'COGRAFI_DUZEY');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 35, 'İbbs-Düzey4 (İlçe)', 'COGRAFI_DUZEY');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 40, 'Büyükşehir Belediye', 'COGRAFI_DUZEY');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 45, 'Belediye', 'COGRAFI_DUZEY');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 50, 'Belde-Köy', 'COGRAFI_DUZEY');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 55, 'Sandık Kurulu', 'COGRAFI_DUZEY');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 60, 'Dağıtımı Yok', 'COGRAFI_DUZEY');