INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 1, 'Adalet Bakanliği Adli Sicil Ve İstatistik Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 2, 'Deneme', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 3, 'Ticaret Bakanliği (Gümrük Ve Ticaret)', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 4, 'Karadeniz Birlik Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 5, 'Balik Hal Ve Tesisleri', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 6, 'Milli Kütüphane Başkanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 7, 'Türkiye Elektrik İletim Anonim Şirketi Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 8, 'Emniyet Genel Müdürlüğü, Jandarma Genel Komutanliği, Adalet Bakanliği Ceza Ve Tevkifevleri Genel Müdürlüğü, Genelkurmay Başkanliği, Tüik Ölüm Nedeni', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 9, 'Yaş Sebze Ve Meyve Halleri', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 10, 'Hazine Ve Maliye Bakanliği (Hazine) Kamu Finansmani Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 11, 'Türkiye İş Kurumu Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 12, 'T.C. Cumhurbaşkanliği Strateji Ve Bütçe Başkanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 13, 'Yükseköğretim Kurulu Başkanliği Kredi Ve Yurtlar Kurumu', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 14, 'Tarim Ve Orman Bakanliği (Orman Ve Su İşleri) Orman Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 15, 'Tarim Sigortalari Havuz İşletmesi Anonim Şirketi', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 16, 'İçişleri Bakanliği Sivil Toplumla İlişkiler Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 17, 'Yükseköğretim Kurulu Başkanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 18, 'Tarim Ve Orman Bakanliği (Gida, Tarim Ve Hayvancilik) Bitkisel Üretim Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 19, 'Devlet Arşivleri Başkanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 20, 'Ulaştirma Ve Altyapi Bakanliği Karayolu Düzenleme Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 21, 'Kültür Ve Turizm Bakanliği Kütüphaneler Ve Yayimlar Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 22, 'Türkiye Cumhuriyet Merkez Bankasi', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 23, 'Sağlik Bakanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 24, 'Tarim Ve Orman Bakanliği (Gida, Tarim Ve Hayvancilik) Gida Ve Kontrol Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 25, 'Tapu Ve Kadastro Genel Müdürlüğü Yabanci İşler Daire Başkanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 26, 'Ticaret Bakanliği Risk Yönetimi Ve Kontrol Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 27, 'Nüfus Ve Vatandaşlik İşleri Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 28, 'Çukobirlik  Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 29, 'Ticaret Bakanliği (Gümrük Ve Ticaret) Esnaf Ve Sanatkarlar Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 30, 'Diyanet İşleri Başkanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 31, 'Tarim Ve Orman Bakanliği (Gida, Tarim Ve Hayvancilik) Şeker Dairesi Başkanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 32, 'Uluslar Arasi Yatirimcilar Derneği (Yased)', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 33, 'Ticaret Bakanliği (Gümrük Ve Ticaret) Esnaf Ve Sanatkarlar Genel Müdürlüğü İç Ticaret Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 34, 'Kültür Ve Turizm Bakanliği Telif Haklari Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 35, 'Sosyal Güvenlik Kurumu', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 36, 'Milli Eğitim Bakanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 37, 'Süs Bitkileri Üreticileri Alt Birliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 38, 'Bankacilik Düzenleme Ve Denetleme Kurumu', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 39, 'Ziraat Bankasi Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 40, 'Sanayi Ve Teknoloji Bakanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 41, 'Emniyet Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 42, 'Milli Eğitim Bakanliği Strateji Geliştirme Başkanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 43, 'Hazine Ve Maliye Bakanliği Muhasebat Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 44, 'Tohum Yetiştiricileri Alt Birliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 45, 'Trakya Birlik Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 46, 'Türkiye Noterler Birliği, Emniyet Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 47, 'Fide Üreticileri Alt Birliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 48, 'Devlet Su İşleri Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 49, 'Vakiflar Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 50, 'Çaykur Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 51, 'Aile, Çalişma Ve Sosyal Hizmetler Bakanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 52, 'Nüfus Ve Vatandaşlik İşleri Genel Müdürlüğü Mekansal Adres Kayit Sistemi (Maks)', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 53, 'Bankacilik Düzenleme Ve Denetleme Kurumu,Sermaye Piyasasi Kurulu, Hazine Ve Maliye Bakanliği (Hazine),Teskomb,Türkiye Cumhuriyet Merkez Bankasi,Türkiye Odalar Ve Borsalar Birliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 54, 'Kültür Ve Turizm Bakanliği Kültür Varliklari Ve Müzeler Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 55, 'Ticaret Bakanliği (Ekonomi)', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 56, 'Ölçme, Seçme Ve Yerleştirme Merkezi Başkanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 57, 'Yüksek Seçim Kurulu Başkanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 58, 'Türkiye Büyük Millet Meclisi Başkanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 59, 'Tarim Ve Orman Bakanliği (Gida, Tarim Ve Hayvancilik)  Toprak Reformu Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 60, 'Türkiye Süt Üreticileri Merkez Birliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 61, 'Çiçek Kooperatifleri', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 62, 'Toprak Mahsülleri Ofisi (Tmo)', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 63, 'Hazine Ve Maliye Bakanliği (Maliye)', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 64, 'Tiftikbirlik', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 65, 'Tarim Ve Kirsal Kalkinmayi Destekleme Kurumu', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 66, 'Tarim Ve Orman Bakanliği (Gida, Tarim Ve Hayvancilik) Tütün Ve Alkol Dairesi Başkanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 67, 'İçişleri Bakanliği Mahalli İdareler Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 68, 'Gülbirlik', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 69, 'Kamu Hastaneleri Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 70, 'Fiskobirlik Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 71, 'Çevre Ve Şehircilik Bakanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 72, 'Kültür Ve Turizm Bakanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 73, 'Tarim Ve Orman Bakanliği (Orman Ve Su İşleri) Bilgi İşlem Daire Başkanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 74, 'Fidan Üreticileri Alt Birliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 75, 'Kültür Ve Turizm Bakanliği Opera Ve Bale Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 76, 'Tarim Ve Orman Bakanliği (Gida, Tarim Ve Hayvancilik) Hayvancilik  Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 77, 'Tapu Ve Kadastro Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 78, 'Tariş', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 79, 'Gelir İdaresi Başkanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 80, 'Kültür Ve Turizm Bakanliği Kütüphane Ve Yayimlar Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 81, 'Emniyet Genel Müdürlüğü, Jandarma Genel Komutanliği, Trafik Sigortalari Bilgi Merkezi (Tramer)', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 82, 'Tapu Ve Kadastro Genel Müdürlüğü (Takbis)', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 83, 'Marmarabirlik', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 84, 'Tarim Ve Kredi Kooperatifleri Merkez Birliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 85, 'Jandarma Genel Komutanliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 86, 'Ticaret Borsalari', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 87, 'Tohum Sanayicileri Ve Üreticileri Alt Birliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 88, 'Tarim Ve Orman Bakanliği (Gida, Tarim Ve Hayvancilik)', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 89, 'Kültür Ve Turizm Bakanliği Güzel Sanatlar Genel Müdürlüğü', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 90, 'Türkiye Odalar Ve Borsalar Birliği', 'KAYNAK_KURUM');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 91, 'Üretici Birlikleri', 'KAYNAK_KURUM');