INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 1, 'EUROSTAT', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 2, 'UNFCCC (Birleşmiş Milletler İklim Değişikliği Çerçeve Sözleşmesi) , EEA (Avrupa Çevre Ajansı)', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 3, 'OECD', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 4, 'UNECE', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 5, 'FAO', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 6, 'Birleşmiş Milletler ve bağlı kuruluşları (WHO,UNICEF,UNDP, UNSD,UNECE vb.)', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 7, 'Avrupa Komisyonu Yıllık Raporları', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 8, 'Dünya Bankası', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 9, 'Birleşmiş Milletler ve bağlı kuruluşları (WHO,UNICEF,UNECE vb.)', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 10, 'Birleşmiş Milletler ve bağlı kuruluşları (WHO,UNICEF,UNSD,UNIGME,UNECE vb.)', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 11, 'IMF', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 12, 'Alüminyum birliği', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 13, 'SESRIC', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 14, 'Birleşmiş Milletler ve bağlı kuruluşları (WHO,UNICEF,UNSD,UNECE vb.)', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 15, 'EİT', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 16, 'UN', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 17, 'Birleşmiş Milletler', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 18, 'ITC-Intracen, IMF, FAO, EİT, IRF (Uluslararası Yol Federasyonu)', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 19, 'DG ECFIN', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 20, 'EKOSOK himayesinde düzenlenen Yüksek Düzeyli Siyasi Forum -HLPF''ye', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 21, 'BM Özelleşmiş Kuruluşlarına: (Bu kuruluşlardan gelen tekil ya da çoklu göstegre bazlı veri talepleri kapsamında iletilmiştir.)', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 22, 'ILO', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 23, 'UNESCO', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 24, 'WHO', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 25, 'UNWTO', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 26, 'EUROSTAT (UOE)', 'KURULUS');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 27, 'International Telecommunication Union (ITU)', 'KURULUS');