INSERT INTO paylasim_kurulus(id, adi) VALUES (1, 'EUROSTAT');
INSERT INTO paylasim_kurulus(id, adi) VALUES (2, 'UNFCCC (Birleşmiş Milletler İklim Değişikliği Çerçeve Sözleşmesi) , EEA (Avrupa Çevre Ajansı)');
INSERT INTO paylasim_kurulus(id, adi) VALUES (3, 'OECD');
INSERT INTO paylasim_kurulus(id, adi) VALUES (4, 'UNECE');
INSERT INTO paylasim_kurulus(id, adi) VALUES (5, 'FAO');
INSERT INTO paylasim_kurulus(id, adi) VALUES (6, 'Birleşmiş Milletler ve bağlı kuruluşları (WHO,UNICEF,UNDP, UNSD,UNECE vb.)');
INSERT INTO paylasim_kurulus(id, adi) VALUES (7, 'Avrupa Komisyonu Yıllık Raporları');
INSERT INTO paylasim_kurulus(id, adi) VALUES (8, 'Dünya Bankası');
INSERT INTO paylasim_kurulus(id, adi) VALUES (9, 'Birleşmiş Milletler ve bağlı kuruluşları (WHO,UNICEF,UNECE vb.)');
INSERT INTO paylasim_kurulus(id, adi) VALUES (10, 'Birleşmiş Milletler ve bağlı kuruluşları (WHO,UNICEF,UNSD,UNIGME,UNECE vb.)');
INSERT INTO paylasim_kurulus(id, adi) VALUES (11, 'IMF');
INSERT INTO paylasim_kurulus(id, adi) VALUES (12, 'Alüminyum birliği');
INSERT INTO paylasim_kurulus(id, adi) VALUES (13, 'SESRIC');
INSERT INTO paylasim_kurulus(id, adi) VALUES (14, 'Birleşmiş Milletler ve bağlı kuruluşları (WHO,UNICEF,UNSD,UNECE vb.)');
INSERT INTO paylasim_kurulus(id, adi) VALUES (15, 'EİT');
INSERT INTO paylasim_kurulus(id, adi) VALUES (16, 'UN');
INSERT INTO paylasim_kurulus(id, adi) VALUES (17, 'Birleşmiş Milletler');
INSERT INTO paylasim_kurulus(id, adi) VALUES (18, 'ITC-Intracen, IMF, FAO, EİT, IRF (Uluslararası Yol Federasyonu)');
INSERT INTO paylasim_kurulus(id, adi) VALUES (19, 'DG ECFIN');
INSERT INTO paylasim_kurulus(id, adi) VALUES (20, 'EKOSOK himayesinde düzenlenen Yüksek Düzeyli Siyasi Forum -HLPF''ye');
INSERT INTO paylasim_kurulus(id, adi) VALUES (21, 'BM Özelleşmiş Kuruluşlarına: (Bu kuruluşlardan gelen tekil ya da çoklu göstegre bazlı veri talepleri kapsamında iletilmiştir.)');
INSERT INTO paylasim_kurulus(id, adi) VALUES (22, 'ILO');
INSERT INTO paylasim_kurulus(id, adi) VALUES (23, 'UNESCO');
INSERT INTO paylasim_kurulus(id, adi) VALUES (24, 'WHO');
INSERT INTO paylasim_kurulus(id, adi) VALUES (25, 'UNWTO');
INSERT INTO paylasim_kurulus(id, adi) VALUES (26, 'EUROSTAT (UOE)');
INSERT INTO paylasim_kurulus(id, adi) VALUES (27, 'International Telecommunication Union (ITU)');