INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 5, 'Aylık', 'PERIYOT');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 10, 'Üç Aylık', 'PERIYOT');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 15, 'Altı Aylık', 'PERIYOT');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 20, 'Yıllık', 'PERIYOT');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 25, 'İki Yıllık', 'PERIYOT');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 30, 'Üç Yıllık', 'PERIYOT');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 35, 'Dört Yıllık', 'PERIYOT');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 40, 'Beş Yıllık', 'PERIYOT');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 45, 'On Yıllık', 'PERIYOT');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 50, 'Belirsiz', 'PERIYOT');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 1, 'Günlük', 'PERIYOT');
INSERT INTO referans(id, kodu, adi, tipi) VALUES (nextval('hibernate_sequence'), 55, 'Dağıtım Yok', 'PERIYOT');